### ISSUE TITLE
Not working the sdk in typescript

### ISSUE THREAD

**Issue by winer328** [wen-moon-ser/moonshot-sdk#16]
I used example code to buy/sell tokens in moonshot.
But not working.
```
Module '"@wen-moon-ser/moonshot-sdk"' has no exported member 'FixedSide'.ts(2305)
import FixedSide
```
```
Module '"@wen-moon-ser/moonshot-sdk"' has no exported member 'Moonshot'.ts(2305)
import Moonshot
```
Why I get this error?
Thanks.

**Comment by mavagio** [comment]
hey @winer328 can you please post a complete code snippet and make sure you install all dependencies similar to example project: https://github.com/wen-moon-ser/moonshot-bot-examples

**Comment by winer328** [comment]
I used example code in the readme.

**Comment by winer328** [comment]
Thanks for your reply.
When I use previous version, it works well.
But when I use latest version, it doesn't work.

**Comment by mavagio** [comment]
can you please post the version you are using that doesn't work ?

**Comment by winer328** [comment]
3.0.1-alpha-0.0.2

**Comment by mavagio** [comment]
please don't use alpha release, use only stable releases, regardless I have tried the 3.0.1-alpha-0.0.2 as well and it works, as a starting  point you can always use this project https://github.com/wen-moon-ser/moonshot-bot-examples

**Comment by winer328** [comment]
> Hi @mavagio How are you?
> 
> I'm having errors to sell tokens, the instruction is "Sell" but I'm not receiving back the SOL
> 
> This is transaction example: [SolScan](https://solscan.io/tx/3FUc6Xcznx7XPQ5wemEdyMwvQbbMg1bztGRkSdC99o21BoFEhQdLP2ZvCviR33u7dRUJfDCSjBSD2fqXi2iuFgSF)
> 
> In the Token Balance Change I can see that everything goes well, but in the Sol Balance Change, I'm not being able to receive the SOL back from the sell.
> 
> I cloned the [moonshot-bot-examples](https://github.com/wen-moon-ser/moonshot-bot-examples) and the same happens.
> 
> [moonshot-bot-examples](https://github.com/wen-moon-ser/moonshot-bot-examples)

I can solve your issue in selling token in moonshot.
Don't worry, I can help you.
Please contact me in TG - @jsrise

**Comment by mavagio** [comment]
> Hi @mavagio How are you?
> 
> I'm having errors to sell tokens, the instruction is "Sell" but I'm not receiving back the SOL
> 
> This is transaction example: [SolScan](https://solscan.io/tx/3FUc6Xcznx7XPQ5wemEdyMwvQbbMg1bztGRkSdC99o21BoFEhQdLP2ZvCviR33u7dRUJfDCSjBSD2fqXi2iuFgSF)
> 
> In the Token Balance Change I can see that everything goes well, but in the Sol Balance Change, I'm not being able to receive the SOL back from the sell.
> 
> I cloned the [moonshot-bot-examples](https://github.com/wen-moon-ser/moonshot-bot-examples) and the same happens.
> 

> [moonshot-bot-examples](https://github.com/wen-moon-ser/moonshot-bot-examples)

<img width="1496" alt="Screenshot 2024-11-28 at 19 54 30" src="https://github.com/user-attachments/assets/6db075c5-7090-4f4a-80fa-8b7e55271b14">

Hey @DamianGuilisasti after reviewing your transaction here is an explanation for you.
Line 1 is how much your signing wallet paid in total and you are right in expecting this balance to be positive, not negative. Line 2 is how much bonding curve account gave SOL to your account. However, you also need to pay gas fee which was in total `0.000045`. Also the protocol charges 1% as a trading fee. The money that you got from the bonding curve is 0.000002866 which was not enough to cover the gas fee and trading fee.
I recommend if you are making a bot, have a minimum amount that you are willing to spend, also use EXACT_OUT on SELL that way the slippage will be applied to the token amount. Before executing a trade you can always estimate the collateral amount you will receive or spend, so you can check in advance if the trade will be profitable or not.
