### ISSUE TITLE
Support to mint moonshot token ? 

### ISSUE THREAD

**Issue by wngasinur** [wen-moon-ser/moonshot-sdk#19]
Any idea is this going to be developed

**Comment by winer328** [comment]
Is this git account dexscreener moonshot dev?

**Comment by mavagio** [comment]
we don't support direct RPC mint however you can technically automate minting using moonshot UI and API endpoints but it's not officially supported for the bots

**Comment by winer328** [comment]
Thanks for your support.
I just want to know you are dex screener main dev or not.
Best regards.

**Comment by mavagio** [comment]
This is now possible via SDK and API endpoint.
